## Ansible Inventory Server image
## ref: https://hub.docker.com/r/cloudeng/ansible-inventory-server/tags
##
ansibleInventoryServerImage:
  registry: docker.io
  repository: cloudeng/ansible-inventory-server
  tag: v1.0
  ## Specify a imagePullPolicy. Defaults to "Always" if image tag is "latest", else set to "IfNotPresent"
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: IfNotPresent
  ## Optionally specify an array of imagePullSecrets (secrets must be manually created in the namespace)
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  # pullSecrets:
  # - myRegistryKeySecretName
