## Ansible Inventory Server image
## ref: https://hub.docker.com/r/cloudeng/ansible-inventory-server/tags
##

image: registry.docker.grnet.gr/sysengteam/ansible-inventory-server:1.1.2
nodePort: 32500
